name: Build and deploy Qt application

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
      - uses: actions/checkout@v2
      
      - name: Setup Qt
        uses: thomaslorentsen/setup-qt@v1
        with:
          qt-version: 6.2.3
      
      - name: Build for Windows
        if: runner.os == 'Windows'
        run: qmake && MSVC2019

