name: Build Qt Project on Windows

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Visual Studio 2019
      uses: microsoft/setup-visual-studio@v1
      with:
        vs-version: 2019

    - name: Install Qt
      uses: jurplel/install-qt-action@v3.0.0
      with:
        version: 6.5.0

    - name: Build project
      run: qmake && nmake
